### ISSUE TITLE
the time used by filter_coords()

### ISSUE THREAD

**Issue by Zuttergutao** [danijoo/xdrfile#14]
Hi! I am using the rust wrapper `xdrfile`, but one problem was encountered.
When i used the function `Frame::filter_coords()` to filter the specified atoms, the time  consumed by every frame was big (7 sec in my system). Have you test this function in a large system?
Appendix:
The system contains 31784 atoms.
filter: Half the atoms in the system.

**Comment by dnlbauer** [comment]
Hi,

this sound unusual too me. I have used this library in the past for the analysis of systems with > 100.000 atoms without seeing such bad performance. Under the hood, it doesnt do much more than selecting elements of the array by their index using rusts stdlib.

It's hard to say something without seeing actual code, but I have some ideas that could help to identify the issue:
- make sure you compile your program with a release profile (set the `opt-level=3` in your `Cargo.toml`). By default, the rust compiler does not do this and there is a huge performance difference.
- performance will depend strongly on how you are using the frames objects yielded during the iteration loop: if you keep any reference to the frame object, the library cannot reuse it. In this case it will instantiate a new one (which means allocating new arrays in memory and being very slow). If you do not keep a reference, it can reuse the old one which makes it several orders of magnitude faster.

**Comment by dnlbauer** [comment]
I mark this as resolved since there wasnt a response for some month.
